version: "3.7"

services:
  php:
    container_name: skeleton_php
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/tmp
  redis:
    container_name: skeleton_redis
    image: redis:latest
    ports:
      - "6949:6379"
