###  GET请求
GET {{ url }}v2/list  HTTP/1.1
content-type: application/json

###  POST请求
POST {{ url }}  HTTP/1.1
content-type: application/json
Cookie: xxx

{
    'id':xxx,
    'name':xx,
    'age':xxx
}
